import { Space } from '../../shared/types.shared';

type SpaceType = {
  id: string;
  name?: string;
  x: number;
  y: number;
  connections: string[];
  labels?: string[];
};

const READONLY_SPACES: SpaceType[] = [
  {
    id: 'q-talo',
    name: 'Q-talo',
    x: 63,
    y: 53,
    connections: [],
    labels: ['bus'],
  },
  {
    id: 'q-talo-yla-1',
    x: 64.1,
    y: 50,
    connections: ['q-talo'],
  },
  {
    id: 'q-talo-yla-2',
    x: 64.8,
    y: 46.9,
    connections: ['q-talo-yla-1'],
  },
  {
    id: 'q-talo-yla-3',
    x: 64.3,
    y: 44.6,
    connections: ['q-talo-yla-2'],
  },
  {
    id: 'q-talo-edusta',
    x: 59.2,
    y: 54.1,
    connections: ['q-talo'],
  },
  {
    id: 'urheilukentta-oikea',
    x: 55.6,
    y: 55.1,
    connections: ['q-talo-edusta'],
  },
  {
    id: 'urheilukentta-vasen',
    x: 51.8,
    y: 56.2,
    connections: ['urheilukentta-oikea', 'urheilukentta'],
  },
  {
    id: 'urheilukentta-hiekka',
    x: 60.5,
    y: 57.2,
    connections: ['urheilukentta'],
  },
  {
    id: 'kuuvuori-alarinne',
    x: 62.7,
    y: 59.7,
    connections: ['urheilukentta-hiekka'],
  },
  {
    id: 'kuuvuori-portaat',
    x: 62.6,
    y: 62,
    connections: ['kuuvuori-alarinne'],
  },
  {
    id: 'kuuvuori-ylarinne',
    x: 58.6,
    y: 62.3,
    connections: ['kuuvuori-portaat'],
  },
  {
    id: 'kuuvuori',
    name: 'Kuuvuori',
    x: 55,
    y: 63.5,
    connections: ['kuuvuori-ylarinne'],
  },
  {
    id: 'kylpyla',
    name: 'Kylpylä',
    x: 26,
    y: 45,
    connections: [],
  },
  {
    id: 'kylpyla-etuparkki',
    x: 26.6,
    y: 50.6,
    connections: ['kylpyla'],
  },
  {
    id: 'kylpyla-takaparkki',
    x: 24.4,
    y: 55.5,
    connections: ['kylpyla-etuparkki'],
  },
  {
    id: 'urheilu-k-market-risteys',
    x: 37,
    y: 61,
    connections: ['urheilukentta-tie-1', 'k-market'],
    labels: ['bus'],
  },
  {
    id: 'urheilukentta',
    name: 'Urheilukenttä',
    x: 56.2,
    y: 58,
    connections: [],
  },
  {
    id: 'urheilukentta-tie-1',
    x: 40.7,
    y: 59.9,
    connections: ['urheilukentta-tie-2'],
  },
  {
    id: 'urheilukentta-tie-2',
    x: 44.4,
    y: 58.6,
    connections: ['urheilukentta-tie-3'],
  },
  {
    id: 'urheilukentta-tie-3',
    x: 48.7,
    y: 57.1,
    connections: ['urheilukentta-vasen'],
  },
  {
    id: 'urheilukentta-kuntosali',
    name: 'Kuntosali',
    x: 50.5,
    y: 58.6,
    connections: ['urheilukentta-tie-3', 'urheilukentta'],
  },
  {
    id: 'k-market',
    name: 'K-market',
    x: 39,
    y: 65,
    connections: [],
  },
  {
    id: 'kirkkotie-ala-1',
    x: 36.5,
    y: 67.9,
    connections: ['k-market'],
  },
  {
    id: 'hautausmaa',
    name: 'Hautausmaa',
    x: 33.4,
    y: 28.9,
    connections: [],
  },
  {
    id: 'posankka',
    name: 'Posankka',
    x: 23.4,
    y: 60.4,
    connections: [],
  },
  {
    id: 'posankka-tie',
    x: 26,
    y: 58.2,
    connections: ['posankka', 'kylpyla-takaparkki'],
  },
  {
    id: 'posankka-tie-alku',
    x: 29.2,
    y: 63,
    connections: ['posankka-tie'],
  },
  {
    id: 'tie-123132131231',
    x: 33.2,
    y: 61.8,
    connections: ['posankka-tie-alku', 'urheilu-k-market-risteys'],
  },
  {
    id: 'kirkkotie-10',
    x: 40.1,
    y: 55.9,
    connections: ['urheilukentta-tie-1'],
  },
  {
    id: 'kirkkotie-30',
    x: 42.1,
    y: 53.9,
    connections: ['kirkkotie-10'],
  },
  {
    id: 'kirkkotie-45',
    x: 43.5,
    y: 50.6,
    connections: ['kirkkotie-30'],
  },
  {
    id: 'kirkkotie-55',
    x: 45.3,
    y: 47.5,
    connections: ['kirkkotie-45'],
  },
  {
    id: 'kirkkotie-70',
    x: 46.1,
    y: 44.2,
    connections: ['kirkkotie-55'],
  },
  {
    id: 'kirkkotie-80',
    x: 46.1,
    y: 41.5,
    connections: ['kirkkotie-70'],
  },
  {
    id: 'kirkkotie-90',
    x: 46.9,
    y: 38.3,
    connections: ['kirkkotie-80'],
  },
  {
    id: 'kirkkotie-100',
    x: 49.4,
    y: 34,
    connections: ['kirkkotie-90'],
  },
  {
    id: 'liukumaki-polku',
    x: 40.8,
    y: 44.9,
    connections: ['kirkkotie-55'],
  },
  {
    id: 'kylpyla-takaosa',
    x: 37.5,
    y: 40.8,
    connections: ['likumaki-polku', 'liukumaki-polku'],
  },
  {
    id: 'hautausmaa-portti',
    x: 33.5,
    y: 36.6,
    connections: ['kylpyla-takaosa'],
  },
  {
    id: 'hautausmaa-etela',
    x: 35.7,
    y: 33.9,
    connections: ['hautausmaa-portti'],
  },
  {
    id: 'hautausmaa-lounas',
    x: 30.4,
    y: 32.1,
    connections: ['hautausmaa-etela', 'hautausmaa'],
  },
  {
    id: 'liukumaki',
    name: 'Liukumäki',
    x: 37,
    y: 46.2,
    connections: ['liukumaki-polku'],
  },
  {
    id: 'aitiopaikka-kaakko',
    x: 20.9,
    y: 45.5,
    connections: ['kylpyla'],
    labels: ['bus'],
  },
  {
    id: 'kylpyla-hese',
    x: 27.7,
    y: 40.8,
    connections: ['kylpyla'],
  },
  {
    id: 'kylpyla-hese-hautausmaa',
    x: 30.7,
    y: 38.1,
    connections: ['kylpyla-hese', 'hautausmaa-portti'],
  },
  {
    id: 'aitiopaikka',
    name: 'Aitiopaikka',
    x: 17,
    y: 42.4,
    connections: ['aitiopaikka-kaakko'],
  },
  {
    id: 'aitiopaikka-luode',
    x: 12,
    y: 41,
    connections: ['aitiopaikka'],
  },
  {
    id: 'ikituuri',
    name: 'Ikituuri',
    x: 10.1,
    y: 44,
    connections: ['aitiopaikka-luode'],
  },
  {
    id: 'kirkko',
    name: 'Kirkko',
    x: 46.8,
    y: 32.7,
    connections: ['kirkkotie-100'],
  },
  {
    id: 'hautausmaa-ita',
    x: 43,
    y: 31.7,
    connections: ['kirkko'],
  },
  {
    id: 'hautausmaa-kaakko',
    x: 39.9,
    y: 27.4,
    connections: ['hautausmaa-ita'],
  },
  {
    id: 'hautausmaa-pohjoinen',
    x: 35.7,
    y: 24.9,
    connections: ['hautausmaa-kaakko', 'hautausmaa'],
  },
  {
    id: 'simolankatu-11',
    x: 48.9,
    y: 49.8,
    connections: ['simolankatu-5'],
  },
  {
    id: 'simolankatu-5',
    x: 46.1,
    y: 52,
    connections: ['kirkkotie-30'],
  },
  {
    id: 'simolankatu-18',
    x: 51.3,
    y: 48.3,
    connections: ['simolankatu-11'],
  },
  {
    id: 'simolankatu-25',
    x: 54.1,
    y: 46.2,
    connections: ['simolankatu-18'],
    labels: ['bus'],
  },
  {
    id: 'simolankatu-risteys',
    x: 58.8,
    y: 43.3,
    connections: ['simolankatu-25'],
  },
  {
    id: 'papinkatu-1',
    x: 51.5,
    y: 34.9,
    connections: ['kirkkotie-100'],
  },
  {
    id: 'papinkatu-5',
    x: 54.5,
    y: 36.7,
    connections: ['papinkatu-1'],
  },
  {
    id: 'papinkatu-10',
    x: 56.4,
    y: 39.4,
    connections: ['papinkatu-5'],
  },
  {
    id: 'papinkatu-15',
    x: 57.7,
    y: 41.3,
    connections: ['papinkatu-10', 'simolankatu-risteys'],
  },
  {
    id: 'papas-pizzeria',
    name: "Papa's Pizzeria",
    x: 61.8,
    y: 42.6,
    connections: ['simolankatu-risteys', 'q-talo-yla-3', 'kuikkulankatu-0'],
  },
  {
    id: 'kuikkulankatu-0',
    x: 63.2,
    y: 40.7,
    connections: [],
  },
  {
    id: 'vpk-metsa',
    x: 37.9,
    y: 54.2,
    connections: ['kirkkotie-10'],
  },
  {
    id: 'vpk-metsa-syva',
    name: 'Metsä',
    x: 34.9,
    y: 51.8,
    connections: ['vpk-metsa'],
  },
  {
    id: 'tyyssija',
    name: 'Tyyssija',
    x: 22.5,
    y: 27.7,
    connections: [],
  },
  {
    id: 'hautausmaa-lounas-kulma',
    x: 27.7,
    y: 29.9,
    connections: ['hautausmaa-lounas'],
  },
  {
    id: 'inspehtori-1',
    x: 10.9,
    y: 39,
    connections: ['aitiopaikka-luode'],
  },
  {
    id: 'inspehtori-2',
    x: 14.6,
    y: 37,
    connections: ['inspehtori-1'],
  },
  {
    id: 'inspehtori-3',
    x: 18,
    y: 34.5,
    connections: ['inspehtori-2'],
  },
  {
    id: 'inspehtori-4',
    x: 21.3,
    y: 32.3,
    connections: ['inspehtori-3'],
  },
  {
    id: 'inspehtori-5',
    x: 24.5,
    y: 30.1,
    connections: ['tyyssija', 'inspehtori-4'],
  },
  {
    id: 'inspehtori-6',
    x: 27.3,
    y: 28.3,
    connections: ['hautausmaa-lounas-kulma', 'inspehtori-5'],
  },
  {
    id: 'aurajoki',
    name: 'Aurajoki',
    x: 13.7,
    y: 16.2,
    connections: [],
  },
  {
    id: 'aurajoen-ranta',
    x: 13.9,
    y: 20,
    connections: ['aurajoki'],
  },
  {
    id: 'aurajoen-ranta-portti',
    x: 16.3,
    y: 22.1,
    connections: ['aurajoen-ranta'],
  },
  {
    id: 'tyyssijan-taka',
    x: 19.8,
    y: 25.4,
    connections: ['aurajoen-ranta-portti'],
  },
  {
    id: 'tyyssija-koillinen',
    x: 24.8,
    y: 24.3,
    connections: ['tyyssijan-taka'],
  },
  {
    id: 'tyyssija-ita',
    x: 26.9,
    y: 26.2,
    connections: ['tyyssija-koillinen', 'inspehtori-6'],
  },
  {
    id: 'tuulitunneli',
    name: 'Tuulitunneli',
    x: 16.1,
    y: 56.8,
    connections: [],
  },
  {
    id: 'tuulitie',
    x: 19.5,
    y: 55.2,
    connections: ['tuulitunneli'],
  },
  {
    id: 'posankka-polku',
    x: 22.5,
    y: 57.6,
    connections: ['tuulitie', 'posankka'],
  },
  {
    id: 'tuulitie-2',
    x: 17.7,
    y: 51.8,
    connections: ['tuulitie'],
  },
  {
    id: 'tuulitie-3',
    x: 16,
    y: 49.1,
    connections: ['tuulitie-2'],
  },
  {
    id: 'tuulitie-4',
    x: 13.6,
    y: 45.9,
    connections: ['tuulitie-3', 'ikituuri'],
  },
  {
    id: 'yo-kyla-lansi',
    name: 'Yo-kylä (länsi)',
    x: 27.2,
    y: 21.8,
    connections: ['tyyssija-koillinen'],
  },
  {
    id: 'yo-kyla',
    name: 'Yo-kylä',
    x: 58.7,
    y: 22.3,
    connections: [],
  },
  {
    id: 'yo-kyla-ulkokuntosali',
    name: 'Ulkokuntosali',
    x: 63.4,
    y: 24,
    connections: ['yo-kyla'],
  },
  {
    id: 'kuikkulankatu-10',
    x: 53.1,
    y: 22.3,
    connections: ['yo-kyla'],
  },
  {
    id: 'kuikkulankatu-8',
    x: 54,
    y: 25.7,
    connections: ['kuikkulankatu-10'],
  },
  {
    id: 'kuikkulankatu-7',
    x: 56.4,
    y: 28.6,
    connections: ['kuikkulankatu-8'],
  },
  {
    id: 'kuikkulankatu-1',
    x: 64.3,
    y: 38.8,
    connections: ['kuikkulankatu-0'],
  },
  {
    id: 'kuikkulankatu-2',
    x: 65.6,
    y: 36.6,
    connections: ['kuikkulankatu-1'],
  },
  {
    id: 'kuikkulankatu-3',
    x: 67.1,
    y: 34.5,
    connections: ['kuikkulankatu-2'],
  },
  {
    id: 'kuikkulankatu-4',
    x: 67.2,
    y: 32.1,
    connections: ['kuikkulankatu-3'],
  },
  {
    id: 'kuikkulankatu-5',
    x: 63.6,
    y: 30.9,
    connections: ['kuikkulankatu-4', 'kuikkulankatu-6'],
  },
  {
    id: 'kuikkulankatu-6',
    x: 59.7,
    y: 29.7,
    connections: ['kuikkulankatu-5', 'kuikkulankatu-7'],
  },
  {
    id: 'pappilanmaki-a',
    x: 40.6,
    y: 23.3,
    connections: ['hautausmaa-pohjoinen'],
  },
  {
    id: 'pappilanmaki-b',
    x: 44.5,
    y: 20.5,
    connections: ['pappilanmaki-a'],
  },
  {
    id: 'pappilanmaki-c',
    x: 48.3,
    y: 18.8,
    connections: ['pappilanmaki-b'],
    labels: ['bus'],
  },
  {
    id: 'inspehtori-kuikkula-risteys',
    x: 51.9,
    y: 20.1,
    connections: ['pappilanmaki-c', 'kuikkulankatu-10'],
  },
  {
    id: 'yo-kyla-parkki-pohjoinen',
    x: 67,
    y: 26.9,
    connections: ['yo-kyla-ulkokuntosali'],
  },
  {
    id: 'yo-kyla-parkki',
    x: 67.9,
    y: 29.5,
    connections: ['kuikkulankatu-4', 'yo-kyla-parkki-pohjoinen'],
  },
];

export type SpaceId = typeof READONLY_SPACES[number]['id'];

// Make sure all connections are 2 way and edit
for (const space of READONLY_SPACES) {
  for (const connection of space.connections) {
    const otherSpace = READONLY_SPACES.find((s) => s.id === connection);
    if (!otherSpace) continue;
    if (!otherSpace.connections.includes(space.id)) {
      otherSpace.connections.push(space.id);
    }
  }
}

export const SPACES = READONLY_SPACES;
