services:
  frontend:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 80:80
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    container_name: server
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express
    expose:
      - 3086
    ports:
      - 3086:3086

networks:
  react-express:
