export const getRandomGamertag = () => {
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const gamerTag = getRandomGamerTagAnyLenght();
    if (gamerTag.length <= 16) {
      return gamerTag;
    }
  }
};

const getRandomGamerTagAnyLenght = () => {
  const randomIndex1 = Math.floor(Math.random() * FIRST_WORDS.length);
  const randomIndex2 = Math.floor(Math.random() * LAST_WORDS.length);
  const firstWords = FIRST_WORDS[randomIndex1];
  const lastWords = LAST_WORDS[randomIndex2];
  const firstArray = Array.isArray(firstWords) ? firstWords : [firstWords];
  const lastArray = Array.isArray(lastWords) ? lastWords : [lastWords];
  const combinedArray = [...firstArray, ...lastArray];
  const lowerCaseWords = combinedArray.map((word) => word.toLowerCase());

  return formatWithRandomCase(lowerCaseWords);
};

function capitalize(word: string) {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

function toPascalCase(words: string[]) {
  return words.map(capitalize).join('');
}

function toCamelCase(words: string[]) {
  return words
    .map((word, index) => {
      if (index === 0) {
        return word;
      }
      return capitalize(word);
    })
    .join('');
}

function toSnakeCase(words: string[]) {
  return words.join('_').toLowerCase();
}

function toCapsSnakeCase(words: string[]) {
  return words.join('_').toUpperCase();
}

function toKebabCase(words: string[]) {
  return words.join('-').toLowerCase();
}

const CASE_FUNCTIONS = [
  toPascalCase,
  toCamelCase,
  toSnakeCase,
  toCapsSnakeCase,
  toKebabCase,
];

function formatWithRandomCase(words: string[]) {
  const randomIndex = Math.floor(Math.random() * CASE_FUNCTIONS.length);
  return CASE_FUNCTIONS[randomIndex](words);
}

const FIRST_WORDS = [
  'Mad',
  'Log',
  'Kahvi',
  'Arch',
  'Koodi',
  'Über',
  '3d',
  '5g',
  '4g',
  ['I', 'am'],
  ['back', 'end'],
  ['front', 'end'],
  'Interface',
  'Import',
  'Export',
  'Function',
  ['export', 'const'],
  ['export', 'default'],
  ['math', 'random'],
  'Cloud',
  ['CI', 'CD'],
  'DevOps',
  'FullStack',
  'Rust',
  'AI',
  'API',
  'TS',
  'JS',
  ['npm', 'i'],
  ['yarn', 'add'],
  ['pnpm', 'add'],
  ['Ctrl', 'alt'],
  'i',
  'Himo',
  'Svelte',
  'Php',
  'sql',
  'matlab',
  'python',
  'Java',
  'C',
  'git',
  ['git', 'push'],
  ['git', 'pull'],
  ['git', 'add'],
  ['git', 'clone'],
  ['force', 'push'],
  'Fetch',
  ['SELECT', 'FROM'],
  ['DROP', 'TABLE'],
  ['DELETE', 'FROM'],
  ['INSERT', 'INTO'],
  'Delete',
  'Update',
  ['object', 'object'],
  'Object',
  'Exec',
  'N',
  'Info',
  'Air',
  'Virtual',
  'Web',
  'XOR',
  'Zero',
  'vim',
  'nano',
  'chmod',
  'ls',
  'cd',
  'mkdir',
  'Rune',
  'One',
  'Stack',
  'kyber',
  'dot',
  ['rm', 'rf'],
  ['div', 'class'],
  ['sudo', 'apt'],
  ['sudo', 'vim'],
  ['throw', 'new'],
  ['else', 'if'],
  ['if', 'else'],
  ['drop', 'type'],
  ['alter', 'table'],
  '4bit',
  '8bit',
  '16bit',
  '32bit',
  '64bit',
  'printf',
  'unzip',
  'grep',
  ['what', 'is'],
  ['where', 'is'],
  ['how', 'to'],
  ['this', 'is'],
  ['js', 'vs'],
  ['git', 'gud'],
  ['www', 'dot'],
  ['new', 'set'],
  ['I', 'hate'],
  ['hue', 'rotate'],
  'wget',
  'www',
  'ssh',
  'ascii',
  'RGB',
  'RGBA',
  'sus',
  'var',
  'OSS',
  'web',
  'anti',
  'malloc',
  'uuid',
  'PC',
  'sudo',
  'infinite',
  'insert',
  'static',
  'gnu',
  'doctype',
  'id',
  'semantic',
  'cli',
  ['btw', 'I', 'use'],
  ['g', 'n', 'u'],
  ['gg', 'wp'],
  'report',
  ['gl', 'hf'],
  ['gg', 'ez'],
  ['pls', 'test'],
  ['pls', 'fix'],
  ['pls', 'exit'],
  ['cs', 'go'],
  'ez',
  'fpt',
  'qa',
  'web3',
  'localhost',
  'unreal',
];

const LAST_WORDS = [
  'ue5',
  'emulator',
  'fedora',
  'ubuntu',
  'gobol',
  'graph',
  ['graph', 'ql'],
  ['ui', 'ux'],
  'emacs',
  'nvim',
  'neovim',
  'vim',
  'vi',
  'react',
  'guuid',
  'uuid',
  'UE6',
  'vscode',
  'cache',
  'xcode',
  'props',
  'state',
  ['uuid', 'v4'],
  ['sys', 'info'],
  ['as', 'const'],
  ['as', 'any'],
  ['as', 'number'],
  ['as', 'string'],
  'reload',
  'console',
  'cors',
  'F4',
  'Koodari',
  'Koodaaja',
  'Table',
  'Random',
  'Star',
  'Teekkari',
  'Koodari',
  'Jappe',
  'JAPPE',
  'Peka',
  'APP',
  'CSS',
  'HTML',
  'USER',
  'Admin',
  'Object',
  'Type',
  'Oksa',
  'Branch',
  'Main',
  'Alt',
  'Delete',
  'Esc',
  'Enter',
  'Space',
  'Tab',
  'Shift',
  'Ctrl',
  'Gamer',
  'PvP',
  '3000',
  'localhost',
  'Head',
  'Div',
  'Span',
  'Button',
  'Input',
  'Form',
  'Html',
  'Return',
  'Break',
  'CONST',
  'plusplus',
  'CONF',
  'JSON',
  'TS',
  'JS',
  'MD',
  'YAML',
  'YML',
  'JPEG',
  'JPG',
  'PNG',
  'GIF',
  'SVG',
  'Integer',
  'String',
  'Boolean',
  'bool',
  'Array',
  'Object',
  'Null',
  'Undefined',
  'NaN',
  'Dom',
  'Bug',
  'prettier',
  'eslint',
  'babel',
  'webpack',
  'parcel',
  'vite',
  'node',
  'pointer',
  ['alt', 'gr'],
  ['Bug', 'fix'],
  ['feat', 'bug'],
  ['unit', 'test'],
  'Infinity',
  'Float',
  'Double',
  'Char',
  'Byte',
  'Short',
  'Long',
  'Void',
  'Function',
  'Class',
  'Interface',
  'Enum',
  'Type',
  'net',
  'Server',
  'Client',
  'DB',
  'Gamer',
  'XD',
  'Figma',
  'UX',
  'KDE',
  'Gnome',
  'Unix',
  'GPU',
  'CPU',
  'RAM',
  'SSD',
  'HDD',
  'Data',
  'xorg',
  'covid',
  'wayland',
  'CEO',
  'CTO',
  'Fuksi',
  'Emulator',
  'Binary',
  'Cache',
  'Compiler',
  'Debugger',
  'Framework',
  'Heap',
  'Library',
  'Network',
  'Operating',
  'Programmer',
  'Protocol',
  'Recursion',
  'player',
  'gamer',
  'Tira',
  'Log',
  'tsx',
  'qubit',
  'addr',
  'text',
  'rsa',
  'Compiler',
  'bios',
  'https',
  'http',
  'xml',
  'SDK',
  'regex',
  'Bash',
  'Zsh',
  'saas',
  'Foss',
  'Error',
  'weleho',
  'Burger',
  'Meme',
  'Titeeni',
  'State',
  'Exe',
  'gui',
  'cli',
  ['dot', 'net'],
  ['dot', 'com'],
  ['r', 's', 'a'],
  ['c', 's', 's'],
];
